In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.feature_selection import SelectFromModel, SelectKBest, chi2
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.ensemble import RandomForestRegressor
df = pd.read_csv('placement.csv')
df1=df
df2=df

In [2]:
scaler = StandardScaler()
df[df.columns] = scaler.fit_transform(df[df.columns])
df

C:\Users\ADIDAS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\extmath.py:1108: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\ADIDAS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\extmath.py:1113: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\ADIDAS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\extmath.py:1133: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count


cgpa   package  f2
0   -0.094213  0.382584 NaN
1   -1.753487 -1.472722 NaN
2    0.777609  0.368090 NaN
3    0.402632  0.976862 NaN
4   -0.047341  0.831917 NaN
..        ...       ...  ..
195 -0.056715 -0.776982 NaN
196 -1.031656 -0.617542 NaN
197  0.205769  0.353595 NaN
198  0.599495  1.397205 NaN
199 -0.722300 -0.965412 NaN

[200 rows x 3 columns]

In [3]:
scaler = MinMaxScaler()
df1[df1.columns] = scaler.fit_transform(df1[df1.columns])
df1

C:\Users\ADIDAS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_array_api.py:472: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmin(X, axis=axis))
C:\Users\ADIDAS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_array_api.py:489: RuntimeWarning: All-NaN slice encountered
  return xp.asarray(numpy.nanmax(X, axis=axis))


cgpa   package  f2
0    0.494361  0.581538 NaN
1    0.161654  0.187692 NaN
2    0.669173  0.578462 NaN
3    0.593985  0.707692 NaN
4    0.503759  0.676923 NaN
..        ...       ...  ..
195  0.501880  0.335385 NaN
196  0.306391  0.369231 NaN
197  0.554511  0.575385 NaN
198  0.633459  0.796923 NaN
199  0.368421  0.295385 NaN

[200 rows x 3 columns]

In [4]:
selector = SelectFromModel(estimator=LinearRegression(), max_features=1)
selector.fit_transform(df[df.columns[:-1]], df['cgpa'])

array([[0.4943609 ],
       [0.16165414],
       [0.66917293],
       [0.59398496],
       [0.5037594 ],
       [0.68233083],
       [0.46428571],
       [0.46804511],
       [0.34398496],
       [0.7612782 ],
       [0.19924812],
       [0.44172932],
       [0.87969925],
       [0.5018797 ],
       [0.65225564],
       [0.56203008],
       [0.48496241],
       [0.21052632],
       [0.5037594 ],
       [0.60526316],
       [0.56766917],
       [0.48684211],
       [0.35338346],
       [0.36278195],
       [0.42669173],
       [0.56766917],
       [0.7612782 ],
       [0.21804511],
       [0.31578947],
       [0.54323308],
       [0.58270677],
       [0.72180451],
       [0.5075188 ],
       [0.39285714],
       [0.57894737],
       [0.4906015 ],
       [0.32518797],
       [0.30827068],
       [0.81954887],
       [0.59586466],
       [0.96240602],
       [0.4943609 ],
       [0.31766917],
       [0.63909774],
       [0.15601504],
       [0.67857143],
       [0.34022556],
       [0.296

In [5]:
from sklearn.preprocessing import LabelEncoder
df2 = pd.read_csv('IRIS.csv')
le=LabelEncoder()
le.fit(df2['species'])
df2=df2.dropna()
sfs = SequentialFeatureSelector(RandomForestRegressor(), n_features_to_select=2)
ad=sfs.fit_transform(df2[df2.columns[:-2]], le.transform(df2['species']))
ad


array([[5.1, 1.4],
       [4.9, 1.4],
       [4.7, 1.3],
       [4.6, 1.5],
       [5. , 1.4],
       [5.4, 1.7],
       [4.6, 1.4],
       [5. , 1.5],
       [4.4, 1.4],
       [4.9, 1.5],
       [5.4, 1.5],
       [4.8, 1.6],
       [4.8, 1.4],
       [4.3, 1.1],
       [5.8, 1.2],
       [5.7, 1.5],
       [5.4, 1.3],
       [5.1, 1.4],
       [5.7, 1.7],
       [5.1, 1.5],
       [5.4, 1.7],
       [5.1, 1.5],
       [4.6, 1. ],
       [5.1, 1.7],
       [4.8, 1.9],
       [5. , 1.6],
       [5. , 1.6],
       [5.2, 1.5],
       [5.2, 1.4],
       [4.7, 1.6],
       [4.8, 1.6],
       [5.4, 1.5],
       [5.2, 1.5],
       [5.5, 1.4],
       [4.9, 1.5],
       [5. , 1.2],
       [5.5, 1.3],
       [4.9, 1.5],
       [4.4, 1.3],
       [5.1, 1.5],
       [5. , 1.3],
       [4.5, 1.3],
       [4.4, 1.3],
       [5. , 1.6],
       [5.1, 1.9],
       [4.8, 1.4],
       [5.1, 1.6],
       [4.6, 1.4],
       [5.3, 1.5],
       [5. , 1.4],
       [7. , 4.7],
       [6.4, 4.5],
       [6.9,

In [6]:

selector = SelectKBest(chi2, k=2)
selector.fit_transform(df2[df2.columns[:-1]], df2['species'])

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,